language: node_js
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_script:
- npm ls >/dev/null
- curl ifconfig.co
install:
- npm install
- gem install travis
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
